apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongos
spec:
  replicas: 2
  selector:
    matchLabels:
      role: mongos
  template:
    metadata:
      labels:
        role: mongos
    spec:
      containers:
        - name: mongos
          image: mongo:4.4
          command: ["mongos", "--configdb", "configReplSet/configsvr-0:27017,configsvr-1:27017,configsvr-2:27017", "--bind_ip_all"]
          ports:
            - containerPort: 27017
