apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shardsvr
spec:
  serviceName: "shardsvr"
  replicas: 3
  selector:
    matchLabels:
      role: shardsvr
  template:
    metadata:
      labels:
        role: shardsvr
    spec:
      containers:
        - name: mongod
          image: mongo:4.4
          command: ["mongod", "--shardsvr", "--replSet", "shardReplSet", "--bind_ip_all"]
          ports:
            - containerPort: 27017
